### ISSUE TITLE
Error using '-ps averages'

### ISSUE THREAD

**Issue by joebowness** [harbourlab/SparK#22]
Hello!

Thanks for making this tool! I have recently discovered it, and mostly it is working great for how I want to visualise my tracks.

The only thing I have not been able to work yet is that when using the '-ps averages' mode, I get this error:

Traceback (most recent call last):
  File "SparK.py", line 622, in <module>
    coords.append([get_relative_hight(np.average(averages)), x_pos])
  File "SparK.py", line 181, in get_relative_hight
    return((raw_value * hight * relative_track_hight_percentage) / max_value) # to not go up to the max
TypeError: unsupported operand type(s) for /: 'float' and 'NoneType'

The same command works perfectly well if I omit the '-ps averages' flag (but it overlays separate tracks for each replicate). Can you give me any insight on what might be going wrong for me here?

Cheers!

**Comment by harbourlab** [comment]
Hey!

Can you send me the complete commands you are using ?

Thanks!

Sent from my iPhone

On Apr 7, 2023, at 3:37 PM, Joe Bowness ***@***.***> wrote:

﻿
CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.

Hello!

Thanks for making this tool! I have recently discovered it, and mostly it is working great for how I want to visualise my tracks.

The only thing I have not been able to work yet is that when using the '-ps averages' mode, I get this error:

Traceback (most recent call last):
File "SparK.py", line 622, in
coords.append([get_relative_hight(np.average(averages)), x_pos])
File "SparK.py", line 181, in get_relative_hight
return((raw_value * hight * relative_track_hight_percentage) / max_value) # to not go up to the max
TypeError: unsupported operand type(s) for /: 'float' and 'NoneType'

The same command works perfectly well if I omit the '-ps averages' flag (but it overlays separate tracks for each replicate). Can you give me any insight on what might be going wrong for me here?

Cheers!

**Comment by joebowness** [comment]
Hi,

Thanks for your quick reply!

This is an example of a command I am using which works - it generates a plot that looks similar to the one I attach here, with the replicates for each condition overlain separately. 

#plot Mecp2
python ~/Resources/Software/SparK/SparK.py \
       -pr chrX:74082000-74088000 \
       -cf ~/SparK_tracks/bedGraph/ATAC_A11B2/17_A11B2_ES_ATAC.sort.chrX.bw.bedGraph.gz  \
       ~/SparK_tracks/bedGraph/ATAC_A11B2/17_A11B2_ES_ATAC.genome1.sort.chrX1.bw.bedGraph.gz  \
       ~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_1d_Rep1.genome1.chrX1.sort.bw.bedGraph.gz ~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_1d_Rep2.genome1.chrX1.sort.bw.bedGraph.gz \
       ~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_3d_Rep1.genome1.chrX1.sort.bw.bedGraph.gz ~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_3d_Rep2.genome1.chrX1.sort.bw.bedGraph.gz \
       ~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_6d_Rep1.genome1.chrX1.sort.bw.bedGraph.gz ~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_6d_Rep2.genome1.chrX1.sort.bw.bedGraph.gz \
       ~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_17d_Rep1.genome1.chrX1.sort.bw.bedGraph.gz ~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_17d_Rep2.genome1.chrX1.sort.bw.bedGraph.gz \
       -tf ~/SparK_tracks/bedGraph/ATAC_A11B2/17_A11B2_ES_ATAC.genome2.sort.chrX1.bw.bedGraph.gz  \
       ~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_1d_Rep1.genome2.chrX1.sort.bw.bedGraph.gz ~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_1d_Rep2.genome2.chrX1.sort.bw.bedGraph.gz \
       ~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_3d_Rep1.genome2.chrX1.sort.bw.bedGraph.gz ~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_3d_Rep2.genome2.chrX1.sort.bw.bedGraph.gz \
       ~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_6d_Rep1.genome2.chrX1.sort.bw.bedGraph.gz ~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_6d_Rep2.genome2.chrX1.sort.bw.bedGraph.gz \
       ~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_17d_Rep1.genome2.chrX1.sort.bw.bedGraph.gz ~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_17d_Rep2.genome2.chrX1.sort.bw.bedGraph.gz \
       -cg 1 2 3 3 4 4 5 5 6 6 -tg 2 3 3 4 4 5 5 6 6 \
       -gl unsplit_ES ES d1 d3 d6 d17 \
       -l g1 g2 -f 191b80 56fcf1 \
       -gtf ~/Resources/gencode.vM25.annotation.chrX.gtf -dg Mecp2 \
       -o plots/A11B2_ATAC_Mecp2

However, when I include the flag "-ps averages” into the command, it produces the error I described. 

In order to save time and memory, I restrict my bedgraph files to only the region of the genome I am interested in (ie. a ~100Mb region of Chromosome X). Could this potentially produce the issue with the averages function? (Maybe it is trying to divide empty regions?) 




Best Wishes,
Joe

[A11B2_ATAC_Mecp2.pdf](https://github.com/harbourlab/SparK/files/11183131/A11B2_ATAC_Mecp2.pdf)

**Comment by harbourlab** [comment]
Maybe.. could you try using the full bedgraphs real quick?

Sent from my iPhone

On Apr 8, 2023, at 5:26 AM, Joe Bowness ***@***.***> wrote:

﻿

Hi,

Thanks for your quick reply!

This is an example of a command I am using which works - it generates a plot that looks similar to the one I attach here, with the replicates for each condition overlain separately.

#plot Mecp2
python ~/Resources/Software/SparK/SparK.py \
-pr chrX:74082000-74088000 \
-cf ~/SparK_tracks/bedGraph/ATAC_A11B2/17_A11B2_ES_ATAC.sort.chrX.bw.bedGraph.gz \
~/SparK_tracks/bedGraph/ATAC_A11B2/17_A11B2_ES_ATAC.genome1.sort.chrX1.bw.bedGraph.gz \
~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_1d_Rep1.genome1.chrX1.sort.bw.bedGraph.gz ~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_1d_Rep2.genome1.chrX1.sort.bw.bedGraph.gz \
~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_3d_Rep1.genome1.chrX1.sort.bw.bedGraph.gz ~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_3d_Rep2.genome1.chrX1.sort.bw.bedGraph.gz \
~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_6d_Rep1.genome1.chrX1.sort.bw.bedGraph.gz ~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_6d_Rep2.genome1.chrX1.sort.bw.bedGraph.gz \
~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_17d_Rep1.genome1.chrX1.sort.bw.bedGraph.gz ~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_17d_Rep2.genome1.chrX1.sort.bw.bedGraph.gz \
-tf ~/SparK_tracks/bedGraph/ATAC_A11B2/17_A11B2_ES_ATAC.genome2.sort.chrX1.bw.bedGraph.gz \
~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_1d_Rep1.genome2.chrX1.sort.bw.bedGraph.gz ~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_1d_Rep2.genome2.chrX1.sort.bw.bedGraph.gz \
~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_3d_Rep1.genome2.chrX1.sort.bw.bedGraph.gz ~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_3d_Rep2.genome2.chrX1.sort.bw.bedGraph.gz \
~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_6d_Rep1.genome2.chrX1.sort.bw.bedGraph.gz ~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_6d_Rep2.genome2.chrX1.sort.bw.bedGraph.gz \
~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_17d_Rep1.genome2.chrX1.sort.bw.bedGraph.gz ~/SparK_tracks/bedGraph/ATAC_A11B2/NPC_17d_Rep2.genome2.chrX1.sort.bw.bedGraph.gz \
-cg 1 2 3 3 4 4 5 5 6 6 -tg 2 3 3 4 4 5 5 6 6 \
-gl unsplit_ES ES d1 d3 d6 d17 \
-l g1 g2 -f 191b80 56fcf1 \
-gtf ~/Resources/gencode.vM25.annotation.chrX.gtf -dg Mecp2 \
-o plots/A11B2_ATAC_Mecp2

However, when I include the flag "-ps averages” into the command, it produces the error I described.

In order to save time and memory, I restrict my bedgraph files to only the region of the genome I am interested in (ie. a ~100Mb region of Chromosome X). Could this potentially produce the issue with the averages function? (Maybe it is trying to divide empty regions?)




Best Wishes,
Joe

**Comment by joebowness** [comment]
I just tried with some full genome-wide bedGraphs, and yes, the averaging seems to work fine. So it probably is a problem related to the fact I was trying to use pre-cropped bedGraph files - I guess I will just have to use the full-size ones.

Thanks again for your help.

**Comment by harbourlab** [comment]
Great! Glad it works now!
Cheers


Sent from my iPhone

On Apr 10, 2023, at 6:12 AM, Joe Bowness ***@***.***> wrote:

﻿

I just tried with some full genome-wide bedGraphs, and yes, the averaging seems to work fine. So it probably is a problem related to the fact I was trying to use pre-cropped bedGraph files - I guess I will just have to use the full-size ones.

Thanks again for your help.
